sudo: required

services:
  - docker

# before_script:
#   - docker pull navono/express-demo || true
# script:
#   - docker build --pull --cache-from navono/express-demo --tag express-demo .

script:
  - docker build --tag express-demo .

after_script:
  - docker images


before_deploy:
  - docker login -u "$USER" -p "$PASS"
deploy:
  provider: script
  scirpt: docker push navono/express-demo
  on:
    branch: master