sudo: required

services:
  - docker

before_script:
  - docker pull navono/express-demo || true
script:
  - docker build --pull --cache-from navono/express-demo --tag navono/express-demo ./src
after_script:
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$USER" -p "$PASS";
    docker push navono/express-demo;
    fi
    
# before_deploy:
#   - docker login -u "$USER" -p "$PASS"
# deploy:
#   provider: script
#   script: docker push navono/express-demo
#   on:
#     branch: master